### ISSUE TITLE
I am Jack Champagne

### ISSUE THREAD

**Issue by bburns-ds** [jack-champagne/cs589-final-project#1]

**Comment by jack-champagne** [comment]
ummmmm, hmmm how should we resolve this

**Comment by bburns-ds** [comment]
@jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne Thoughts?? @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne @jack-champagne
